# Generated by Django 5.0.4 on 2024-04-16 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_users_idusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='medecin',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField(default='')),
                ('date_de_naissance', models.DateField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.users',),
        ),
    ]
