# Generated by Django 5.0.4 on 2024-04-17 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medecin'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(default=0)),
                ('poid', models.FloatField(default=0.0)),
                ('taille', models.FloatField(default=0.0)),
                ('mobile', models.IntegerField(default=0)),
                ('allergies', models.CharField(default='', max_length=50)),
                ('groupe_sanguin', models.CharField(default='', max_length=5)),
                ('date_de_naissance', models.DateField(default='')),
                ('idmed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medecin')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.users',),
        ),
    ]
