# Generated by Django 5.0.4 on 2024-04-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='type_diabete',
            field=models.CharField(default='', max_length=10),
        ),
    ]
