# Generated by Django 5.0.4 on 2024-04-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_patient_type_diabete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='poid',
            new_name='poids',
        ),
    ]
