# Generated by Django 5.0.4 on 2024-04-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_poid_patient_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(default='', max_length=10),
        ),
    ]
