# Generated by Django 5.0.4 on 2024-04-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_patient_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
