# Generated by Django 5.0.4 on 2024-04-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='idmed',
            field=models.ForeignKey(db_column='idmed_id', on_delete=django.db.models.deletion.CASCADE, to='api.medecin'),
        ),
    ]
