# Generated by Django 5.0.4 on 2024-04-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_consultations'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='bilan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bilans/'),
        ),
    ]
