# Generated by Django 5.0.4 on 2024-04-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_consultations_bilan_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='bilan_pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='bilans/'),
        ),
    ]
